/**
 * generated by Xtext 2.19.0
 */
package es.us.isa.idl;

import es.us.isa.idl.IDLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IDLStandaloneSetup extends IDLStandaloneSetupGenerated {
  public static void doSetup() {
    new IDLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
