/*
 * generated by Xtext 2.19.0
 */
package es.us.isa.idl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIDLScopeProvider extends DelegatingScopeProvider {
}
